name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag soer7022/bjarke-bot:$(date +%s)
    - name: Publish the Docker image
      run: docker push soer7022/bjarke-bot
